### ISSUE TITLE
License file doesn't exist

### ISSUE THREAD

**Issue by ktateish** [mhayashi1120/Gauche-dbd-sqlite3#1]
It seems copyright and license are unclear for this software.
Could you add any files to be clear about it?

FYI: Gauche is distributed under 3-clause BSD License,  SQLite3 is in the public domain.

**Comment by mhayashi1120** [comment]
This module is originally downloaded from here http://uchizono.com/wiki/wiliki.cgi?Gauche-dbd.sqlite3

I found the author's email address in the top page.
Now I'm trying to contact the original author. 
Please wait.

**Comment by ktateish** [comment]
Thanks for that.  I'll wait it.

**Comment by mhayashi1120** [comment]
This repository is archived cause of this issue.
 I've created new one.
https://github.com/mhayashi1120/Gauche-dbd-sqlite
